### ISSUE TITLE
crm deal with products

### ISSUE THREAD

**Issue by jmoyanob** [akopkesheshyan/bitrix24-python-rest#10]
Hi, 

I was trying to get a deal list with their products names and prices. 
I can get the product list for one ID. ('crm.deal.productrows.get')

Is there anyway to get a list of every deal (ID) with their products?

thanks

**Comment by akopdev** [comment]
@jmoyanob seems like bitrix doesn't provide such endpoint. You have to grab product list for each deal by one.
