### ISSUE TITLE
GET method is always used

### ISSUE THREAD

**Issue by ipeterov** [akopkesheshyan/bitrix24-python-rest#11]
https://github.com/akopkesheshyan/bitrix24-python-rest/blob/master/bitrix24/bitrix24.py#L87
Let's say I'm calling `crm.deal.add`. `method.rsplit('.', 1)[0]` will compute to `crm.deal`.

Looks like this is not breaking stuff, since Bitrix accepts GET requests even for methods like `crm.deal.add` and `crm.deal.productrows.set`.

My suggestions:
A: Embrace it. Always use GET for all methods since it works. Remove POST-specific code.
B: Fix it. Check `method.rsplit('.', 1)[1]`. Also add `data=p.encode('utf-8')` to post version since it doesn't work with cyrillic symbols.

I don't feel competent enough to chose between these options though.

**Comment by akopdev** [comment]
Hi, thank you for sharing your feedback, proposed logic was implemented in the last update (v2). I'm going to close this issue.
