### ISSUE TITLE
crm.activity.add problem on "START_TIME" and "STOP_TIME"

### ISSUE THREAD

**Issue by ezero0** [akopkesheshyan/bitrix24-python-rest#15]
the method call asks me for the START_TIME field.

The date is structured as "2021-04-05T14: 00: 00-00: 00" which is the way indicated by the REST api, however when executing it, the activity arrives but not its start date or its deadline.

Clarify that the date is formatted as str

**Comment by akopdev** [comment]
Can you provide code sample of request?

**Comment by ezero0** [comment]
> Can you provide code sample of request?

Thanks, look: 
![start_time](https://user-images.githubusercontent.com/45215336/113603848-115bcb80-960a-11eb-9afe-25931ff43ed3.PNG)

How it looks:

![image](https://user-images.githubusercontent.com/45215336/113603984-42d49700-960a-11eb-9221-063ac80a5b7c.png)

What I am doing is by means of a cycle to go through each record of a dataframe and obtain a field that has a date, to this date I concatenate the letter "T" and add the "-00: 00" at the end, as you indicates rest api in your javascript example.

If you require more feedback, please tell me. I thank you in advance for your prompt response.

**Comment by akopdev** [comment]
According to bitrix documentation it should be a valid datetime (https://training.bitrix24.com/rest_help/crm/rest_activity/crm_activity_fields.php)

In most cases ISO 8601 should work for you, for example

`2012-04-23T18:25:43.511Z`

However you also can pass datetime as

`23.04.2012 18:25:43`

Personally I recommend to stick with iso 8601, that should be encoded from the box.

**Comment by ezero0** [comment]
No, not work.

I have tried in various ways.
datetime.datetime.now (). isoformat ()
sfrftime
text string of the form "YYYY-MM-DDTHH-MM: SS"

And nothing works, it is curious that executing the webhook from the url in the browser does it. And the way I put the star_time in the url is: 2021-03-20T13: 00

**Comment by ezero0** [comment]
SORRY!.

It works with isoformat (), I had a parenthesis that came from COMMUNICATIONS that the start_time fields did not work, really an apology and I thank you for all your attention supporting me. Your project is great.
