### ISSUE TITLE
connection contacts and company when adding new deals and companies

### ISSUE THREAD

**Issue by Zesheng-Xu** [akopkesheshyan/bitrix24-python-rest#17]
Hi, first of all, thank you for making this, really making life easier for all of us trying to use the API. I am trying to create new contacts, companies, and new deals using the python code, however, one problem I am running into is that I can not connect the contacts with the deals or companies, because the "Contact_ID" field is read-only and it is an integer, so I am wondering is there a possible way to connect them through code rather than going to bittrix24 and link them one by one.

**Comment by ezero0** [comment]
Hello, I am not the developer of this API but I will try to help you.

What do you mean that contact_id is read-only? Do you have a screenshot with the error?

**Comment by Zesheng-Xu** [comment]
Hi thank you for the response, I got the conclusion that because of when creating a contact, the field "ID" is read-only according to the API documentation by the bitrix24 themselves. I mean yes you can assign "contact_ID" when creating a deal or company, but if I am trying to create a deal and a contact at the same time, it is impossible to link the contact to said deal. 
*edited for grammar and clearity

**Comment by Zesheng-Xu** [comment]
and sorry I dont really have an error screenshot, just a bunch of deals created with no contacts assigned to them.

**Comment by ezero0** [comment]
Ok then I will present you with a flow that may help you.

Suppose that from your application you create a negotiation and a contact at the same time. What you should do is the following:

1.- Create the contact: crm.contact.add, this method will respond to you with the created contact identifier. Save it in a variable (contact_p for example) in python.

2. Create the negotiation: crm.deal.add fill in the data you require and in CONTACT_ID assign it contact_p.

**Comment by Zesheng-Xu** [comment]
wow, that was such an eye-opener, I never thought of that !!! Thank you so much, if you don't mind, can I ask another question?

**Comment by ezero0** [comment]
Yes

**Comment by Zesheng-Xu** [comment]
Thank you! it's about deals. So I was able to create a list of deals, but the amount field was empty.  So I think it is connected with crm.quote, but I tried linking them to each other but on bitrix page, the amount is still 0. So now I am confused, if not quote then what?

**Comment by Zesheng-Xu** [comment]
nvm I figured it out, its crm.deal.productrows.set ! 
Sorry about the trouble, thank you!

**Comment by ezero0** [comment]
Ok. It was a pleasure to help you.
