### ISSUE TITLE
wrong parameter name in method.

### ISSUE THREAD

**Issue by SMoazzamR** [akopkesheshyan/bitrix24-python-rest#19]
I am trying to get the SKUs data from bitrix24 but when requests the endpoint it throws an error.
![image](https://user-images.githubusercontent.com/58803788/170897145-2cbd2c6d-f8a6-41cd-88d1-093f5ea16c58.png)
python api call as follows:
![image](https://user-images.githubusercontent.com/58803788/170897250-af54bf48-46e5-445d-b003-34576ba48415.png)

other methods are working fine forexample:
![image](https://user-images.githubusercontent.com/58803788/170897199-f326ff2f-fbd3-4f08-9041-5246c4869d77.png)

**Comment by ezero0** [comment]
I see the documentation api rest.

And i see that "owner_type" is in "filter" and i can't see a parameter "filter" in your webhook.

https://training.bitrix24.com/rest_help/crm/productrow/crm_item_productrow_list.php

**Comment by akopdev** [comment]
You can define it as a dictionary

b24.callMethod("some.method.name", FILTER={"owner_type": 1}}

**Comment by SMoazzamR** [comment]
The issue is the parameter name.
I had also tried with a dictionary but unable to access API endpoint "crm.item.productrow.list".
Please help. 


![image](https://user-images.githubusercontent.com/58803788/184707899-817c5272-35ee-4eb3-84ea-8a0ed2fdaad5.png)

**Comment by ezero0** [comment]
Hello.

I test the same webhook but in the web browser and i have the same error. This indicates that error dont be part of the Python Library, the problem is from API Rest of Bitrix24. 

I suggest you comunnicate to BX24 support if you can.

**Comment by SMoazzamR** [comment]
Yeah, exactly make sense.
Thank you so much for your time and responses.
I will contact Bitrix24 for that.
