### ISSUE TITLE
How can i send message from chat

### ISSUE THREAD

**Issue by rasperepodvipodvert** [akopkesheshyan/bitrix24-python-rest#4]
https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=93&LESSON_ID=7881#onimbotmessageadd

**Comment by akopdev** [comment]
Hi, according to bitrix documentation, you can't use webhooks for defining events. You have to create an application (and use oAuth2 authorisation pattern), then you will be able to call Bitrix API with auth param.

Currently this library doesn't support that scenario.
