### ISSUE TITLE
Is "catalog.price.list" method should be working?

### ISSUE THREAD

**Issue by baturinivan** [akopkesheshyan/bitrix24-python-rest#5]
Метод REST API catalog.price.list(select, filter, order, navigation) [https://dev.1c-bitrix.ru/rest_help/catalog/price/catalog_price_list.php] похоже не работает. 
Он не ждет start, а использует другой параметр navigation и при попытке получить все цены (без фильтра) дает неверный результат. Конкретно у меня без указания productId дает всего одну запись. Если запрашивать для одного товара - выдает. 
Есть еще методы с аналогичным типом выдачи в REST API.

**Comment by akopdev** [comment]
Данный метод имеет свою собственную семантику запроса. 
Ее можно повторить существующими инструментами, например:

```python
bx24.callMethod('catalog.price.list', start=2, filter={'price':100})
```
