### ISSUE TITLE
Im and chats won't work. 

### ISSUE THREAD

**Issue by inlarin** [akopkesheshyan/bitrix24-python-rest#6]
Hi. IM and chats won't work for me Tried
bx24.callMethod('im.message.add', fields={'DIALOG_ID': '4', 'MESSAGE': 'Bla-bla-bla'})
bx24.callMethod('im.notify', fields={'TO': '4', 'MESSAGE': 'Bla-bla-bla'})
bx24.callMethod('im.notify.personal.add', fields={'USER_ID': '4', 'MESSAGE': 'Bla-bla-bla'})
always retuns "bitrix24.exceptions.BitrixError: User ID can't be empty"
All other methods like post new tasks or seaching by fields in client cards work like charm.
Any advice?

**Comment by akopdev** [comment]
Hi, seems like you have a wrong call. Try

```python
bx24.callMethod('im.message.add', DIALOG_ID=4, MESSAGE='bla bla lba')
```

in response you will get id of message
