### ISSUE TITLE
disk.folder.uploadfile

### ISSUE THREAD

**Issue by ezero0** [akopkesheshyan/bitrix24-python-rest#8]
how to send a file with the disk.folder.uploadfile method

the file is stored in the same folder as the python script.

special emphasis on how I should put the "fileContent" section

**Comment by akopdev** [comment]
Hi, according to Bitrix source codes, you have to pass base64 encoded body of your file.

The final request should be something like this:

```python
bx24.callMethod('disk.storage.uploadfile',
                id=1,
                data ={'NAME': '1.gif'},
                fileContent='R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=­=')
```

**Comment by ezero0** [comment]
Thanks

**Comment by ezero0** [comment]
The method indicate me this error:

"QUERY_LIMIT_EXCEECED "


archivo = open ("output.pdf","rb")
archivo_read=archivo.read()
archivo_base64=base64.encodestring(archivo_read)

print(bx24.callMethod('disk.folder.uploadfile', id=58878, data={'NAME':'Reporte_tickets.pdf'}, fileContent=archivo_base64))
